# Matrices

In [55]:
import numpy as np

A = np.array([[1, 4], [1, 6]])

In [56]:
A.shape # gives the dimension of the matrix

(2, 2)

In [57]:
A.transpose() # or C.T

array([[1, 1],
       [4, 6]])

In [58]:
A.trace()

7

In [59]:
np.linalg.det(A)

2.0

In [60]:
np.linalg.inv(A)

array([[ 3. , -2. ],
       [-0.5,  0.5]])

In [24]:
A.diagonal()

array([ 2, -6])

In [33]:
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
C

array([[11,  1],
       [ 8,  0]])

### Access matrix elements, rows and columns

In [7]:
A = np.array([2, 4, 6, 8, 10])

print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element 

A[0] = 2
A[2] = 6
A[-1] = 10


In [8]:
A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)

A[0] = [ 1  4  5 12]
A[2] = [-6  7 11 19]
A[-1] = [-6  7 11 19]


In [9]:
A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)

A[:,0] = [ 1 -5 -6]
A[:,3] = [12  0 19]
A[:,-1] = [12  0 19]


In [11]:
# Slicing of a Matrix
A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print(A[:2, :4])  # two rows, four columns

[[ 1  4  5 12]
 [-5  8  9  0]]


### Matrix Multiplication

In [13]:
A = np.array([
    [1,2],
    [2,3]
])
B = np.array([
    [-1,0],
    [2,4]
])
np.matmul(A,B)

array([[ 3,  8],
       [ 4, 12]])

In [15]:
A*B # note that this is not matrix multiplication

array([[-1,  0],
       [ 4, 12]])

In [17]:
A.dot(B) # however, this is also matrix multiplication, as Dr. Sethu has noted in his lecture

array([[ 3,  8],
       [ 4, 12]])

### Eigenvalue & Eigenvectors

In [61]:
from numpy import linalg as la # note that now we have imported the module

In [65]:
w, v = la.eig(A)
print("Eigenvalues:", w)
print("Eigenvectors:", v)

Eigenvalues: [0.29843788 6.70156212]
Eigenvectors: [[-0.98496508 -0.57432028]
 [ 0.17275355 -0.81863069]]


__Remark:__ Be careful about round-off error!

If the matrix is symmetrix, you can also use an usefull function `linalg.eigh` (h means Hermitian, which is a complex symmetrix matrix)

In [68]:
S = A + A.transpose() # just generating a symmetric matrix
S

array([[ 2,  5],
       [ 5, 12]])

In [69]:
w, v = la.eigh(S)
print("Eigenvalues:", w)
print("Eigenvectors:", v)

Eigenvalues: [-0.07106781 14.07106781]
Eigenvectors: [[-0.92387953  0.38268343]
 [ 0.38268343  0.92387953]]


In [70]:
la.norm(A) # sometimes you will need it in future

7.3484692283495345